from __future__ import annotations

# Immutable set of allowed case types migrated from case-types.txt
CASE_TYPES: frozenset[str] = frozenset({
    "Adml.S.",
    "AFA",
    "AFFD",
    "APPEAL (ICA)",
    "AR",
    "Arb.A",
    "Arb.P.",
    "AS",
    "ASA",
    "Bail Appl.",
    "Bkg.P",
    "Cal. Case",
    "CC",
    "CCC",
    "CDAR",
    "CDB",
    "CDIR",
    "CDSR",
    "C.E.Appeal",
    "CE.Ref.",
    "CMA",
    "CMC",
    "CMCP",
    "CMP",
    "CMR",
    "CO",
    "CO.ADJ.APPEAL",
    "Co.Appeal",
    "Co.Appl.",
    "Co.Case",
    "Coml.A",
    "COMPLAINT NO",
    "Con.APP(C)",
    "Con.Case(C)",
    "Cont.Cas.(Crl.)",
    "Co.Pet",
    "CRA(V)",
    "CRL.A",
    "Crl.Compl.",
    "Crl.L.P.",
    "Crl.MC",
    "Crl.RC",
    "CRL.REF",
    "Crl.Rev.Pet",
    "CRP",
    "CRP(LR)",
    "CRP(UTY)",
    "CRP(WAKF)",
    "CS",
    "CSDA",
    "Cus.Appeal",
    "Cus.Ref.",
    "DB",
    "DBA",
    "DBAR",
    "DBC",
    "DBP",
    "DIR",
    "DSR",
    "EDA",
    "EDR",
    "EFA",
    "El.Pet.",
    "EP(ICA)",
    "ESA",
    "Ex.Appl.",
    "Ex.FA",
    "Ex.P",
    "Ex.SA",
    "FA",
    "F.A (ADMIRALTY)",
    "FAO",
    "F.A.O (ADMIRALTY)",
    "FAO (RO)",
    "Gen.Report",
    "GTA",
    "GTR",
    "Gua.P.",
    "HPCR(S)",
    "IA",
    "ICR (Crl.MC)",
    "ICR (CRP)",
    "ICR (MACA)",
    "ICR (Mat.Appeal)",
    "ICR (MFA (FOREST))",
    "ICR (OP(ATE))",
    "ICR (OP(C))",
    "ICR (OP(KAT))",
    "ICR (OP (RC) )",
    "ICR (OT.Rev)",
    "ICR (RP)",
    "ICR (WA)",
    "ICR (WP(C))",
    "ICR (WP(Crl.))",
    "Ins.APP",
    "Intest.Cas.",
    "ITA",
    "ITR",
    "JPP",
    "LAAP",
    "LA.App.",
    "MAC",
    "MACA",
    "MA (EXE.)",
    "Mat.Appeal",
    "Mat.Cas",
    "Mat.Ref.",
    "MCA",
    "MEMO",
    "MFA",
    "MFA (ADL)",
    "MFA (ADR)",
    "MFA (COPYRIGHT)",
    "MFA (ECC)",
    "MFA (ELECTION)",
    "MFA (ELECTRICITY)",
    "MFA (FCRA)",
    "MFA (FEMA)",
    "MFA (FERA)",
    "MFA (FINANCE)",
    "MFA (FOREST)",
    "MFA (GST)",
    "MFA (G & W)",
    "MFA (HRCE)",
    "MFA (IDPA)",
    "MFA (INSOLVENCY)",
    "MFA (KEA)",
    "MFA(KME)",
    "MFA (LUNACY)",
    "MFA (MHA)",
    "MFA MT (OP)",
    "MFA (PANCHAYAT)",
    "MFA (PATENTS)",
    "MFA (PROBATE)",
    "MFA (RCT)",
    "MFA (SCSTCC)",
    "MFA (SEBI)",
    "MFA (SUCCESSION)",
    "MFA (TCHRI)",
    "MFA (TCRA)",
    "MFA (TRADE MARKS)",
    "MFA (WAQF)",
    "MFCA",
    "MITA",
    "MJC",
    "MSA",
    "MSA(FS)",
    "NO",
    "OP",
    "OP(AFT)",
    "OP(ATE)",
    "OP(C)",
    "OP (CAT)",
    "OP(Crl.)",
    "OP (DRT)",
    "OP (FC)",
    "OP(FT)",
    "OP(ICA)",
    "OP(KAT)",
    "OP(LC)",
    "OP (MAC)",
    "OP(NCDRC)",
    "OP (RC)",
    "OP STAT",
    "OP (TAX)",
    "OP (WAKF)",
    "OS",
    "OT.Appeal",
    "OT.Appl.",
    "OTC",
    "OTR",
    "OT.Rev",
    "PA",
    "RC",
    "RCRev.",
    "Report",
    "RFA",
    "RFA (MISC.)",
    "RP",
    "RPAR",
    "RPFC",
    "RPJJ",
    "RRPT",
    "RSA",
    "RT",
    "SA",
    "SCA",
    "SCLP",
    "SLP",
    "SP.JC",
    "SRDB",
    "SSCR",
    "ST.Appl.",
    "ST.Ref.",
    "ST.Rev.",
    "Suo Motu Ref.",
    "TDAR",
    "TDB",
    "TDIR",
    "TDSR",
    "Test.Cas",
    "TIP",
    "Tr.Appeal(C)",
    "Tr.Appl. (CR)",
    "TRC",
    "Tr.P(C)",
    "Tr.P(Crl.)",
    "UNN.ADML.S",
    "Unn.CRP Uty",
    "UNN.FAO (RO)",
    "UNNUMB.AFA",
    "UNNUMB.AR",
    "UNNUMB.Arb.A.",
    "UNNUMB.AS",
    "UNNUMB.Bail Appl.",
    "UNNUMB.CB",
    "UNNUMB.CC",
    "UNNUMB.CCC",
    "UNNUMB.CDB",
    "UNNUMB.CEA",
    "UNNUMB.Ce.Ref",
    "UNNUMB.CMA",
    "UNNUMB.CMC",
    "UNNUMB.CMCP",
    "UNNUMB.CMP",
    "UNNUMB.CMR",
    "UNNUMB.CO",
    "UNNUMB.COA",
    "UNNUMB.Co.Appl.",
    "UNNUMB.Con.Case(C)",
    "UNNUMB.Cont.App(C)",
    "UNNUMB.Cont.Cas.(Crl",
    "UNNUMB.CP",
    "UNNUMB.CRA(V)",
    "UNNUMB.CRL.A",
    "UNNUMB.Crl.Compl.",
    "UNNUMB.Crl.L.P.",
    "UNNUMB.Crl.MC",
    "UNNUMB.Crl.RC",
    "UNNUMB.Crl.Rev.Pet",
    "UNNUMB.CRP",
    "UNNUMB.CS",
    "UNNUMB.CUA",
    "UNNUMB.Cus.Ref.",
    "UNNUMB.DBA",
    "UNNUMB.DBC",
    "UNNUMB.DBP",
    "UNNUMB.EDA",
    "UNNUMB.EDR",
    "UNNUMB.EFA",
    "UNNUMB.EP",
    "UNNUMB.EP(ICA)",
    "UNNUMB.ESA",
    "UNNUMB.Ex.FA",
    "UNNUMB Ex.P",
    "UNNUMB.ExSA",
    "UNNUMB.FA",
    "UNNUMB.FAO",
    "UNNUMB.GTA",
    "UNNUMB.GTR",
    "UNNUMB.Gua.P.",
    "UNNUMB.Ins.APP",
    "UNNUMB.Intest Cas.",
    "UNNUMB.ITA",
    "UNNUMB.ITR",
    "UNNUMB.LAA",
    "UNNUMB.LAAP",
    "UNNUMB,MACA",
    "UNNUMB.MA (EXE.)",
    "UNNUMB.Mat.App.",
    "UNNUMB.Mat.Ref.",
    "UNNUMB.MC",
    "UNNUMB.MCA",
    "UNNUMB.MFA",
    "UNNUMB.MFA(KME)",
    "UNNUMB.MFA MT (OP)",
    "UNNUMB.MJC",
    "UNNUMB.MSA",
    "UNNUMB.MSA(FS)",
    "UNNUMB.OP",
    "UNNUMB.OP(AFT)",
    "UNNUMB.OPC",
    "UNNUMB.OPCAT",
    "UNNUMB.OP(Crl.)",
    "UNNUMB.OP DRT",
    "UNNUMB.OPFC",
    "UNNUMB.OP(ICA)",
    "UNNUMB.OP MACT",
    "UNNUMB. OP(RC)",
    "UNNUMB.OP (TAX)",
    "UNNUMB.OS",
    "UNNUMB.OTAP",
    "UNNUMB.OT.Appl",
    "UNNUMB.OTC",
    "UNNUMB.OTRV",
    "UNNUMB.RC",
    "UNNUMB.RC.Rev.",
    "UNNUMB.RFA",
    "UNNUMB.RP",
    "UNNUMB.RPAR",
    "UNNUMB.RPFC",
    "UNNUMB.RPJJ",
    "UNNUMB.RSA",
    "UNNUMB.RT",
    "UNNUMB.SA",
    "UNNUMB.SCA",
    "UNNUMB.SCLP",
    "UNNUMB.SMR",
    "UNNUMB.SP.JC.",
    "UNNUMB.ST.Appl.",
    "UNNUMB.ST.Ref.",
    "UNNUMB.ST.Rev.",
    "UNNUMB.TAC",
    "UNNUMB.TDB",
    "UNNUMB.Test.Cas.",
    "UNNUMB.Tr.Appl. (CR)",
    "UNNUMB.TRC",
    "UNNUMB.TrP(C)",
    "UNNUMB.Tr.P(Crl.)",
    "UNNUMB.UNNUMB.Co.App",
    "UNNUMB.WA",
    "UNNUMB.WAKF",
    "UNNUMB.WP(AFT)",
    "UNNUMB.WP(C)",
    "UNNUMB.WP(Crl.)",
    "UNNUMB.WTA",
    "UNNUMB.WTR",
    "WA",
    "W.C.C.Ref.",
    "WP(AFT)",
    "WP(C)",
    "WP(Crl.)",
    "WP(PIL)",
    "WTA",
    "WTR",
    "ZCOAA",
    "ZCRP(LR)",
    "ZCRP(WK)",
    "ZOP(FT)",
    "ZOP(KAT)",
    "ZOP STAT",
    "ZRFA(MISC.)",
})

__all__ = ["CASE_TYPES"]


